apiVersion: apps/v1
kind: Deployment
metadata:
  name: democommerce
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: democommerce
  template:
    metadata:
      labels:
        app: democommerce
    spec:
      containers:
        - name: democommerce
          image: democommerce:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: democommerce-balancer
spec:
  selector:
    app: democommerce
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
